# Generated by Django 4.1.2 on 2023-02-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_delete_session_year'),
    ]

    operations = [
        migrations.RenameModel('Course','Branch')
    ]
