# Generated by Django 4.1.2 on 2023-02-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20230226_1302'),
    ]

    operations = [
        migrations.RenameField('Student', 'course_id', 'branch_id'),
    ]
