# Generated by Django 4.1.2 on 2023-03-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20230226_1312'),
    ]

    operations = [
        migrations.RenameModel('Student', 'Student_list')
    ]
