# Generated by Django 4.1.2 on 2023-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_stuednt_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuednt_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
